### ISSUE TITLE
Windows support : fail to build with  "Error: Cannot find module '../../package'

### ISSUE THREAD

**Issue by lorenzotsi** [crcn/nexe#57]
A node app based on express & mongodb, fails to build with the attached log (it seems it cannot read packages.json properties (i.e. version)).

I have not experience with nexe, so it is possible I'm missing something.
Thanks
Lorenzo
![buildfail](https://cloud.githubusercontent.com/assets/7831011/3211587/d87378cc-ef21-11e3-99fe-90c6401ad586.png)

**Comment by CKarper** [comment]
I can repro this..   It's in an express package.  It seems to be failing on any require that refers to a json file without extension..    So, that's a require('../../package')...    But it's not finding package.json, presumably it's looking for package.js and failing.   

I can repro this by doing a require to a .json of my own without using the extension...   This is holding me up, and why I had forked the project. 

Now that I see it's under active development again, I'd be happy to help.

**Comment by RainbowDashDC** [comment]
@CKarper Thanks for the info, I'm trying my best to sort out the "mess" this project has been left in, any help is appreciated. As this is, obviously, a big issue I'll see what I can do about this but if you want to go ahead and patch this (i'd presume it's in `bundle.js`) feel free because my major focus is adding native module support right now.

Regardless, thanks for the info!

**Comment by CKarper** [comment]
Looks like it's a module-deps issue.   
I can repro this with a simple app just pointing to stylus.   How do I handle an upstream issue?   I can submit a pull req to them, but if they're slow going, do we monkey patch it or something?  Ugh.

**Comment by RainbowDashDC** [comment]
I'd submit a pull request but while we wait we work on a method that assumes it won't be fixed soon just incase it takes along time.
