### ISSUE TITLE
Feature request: cross-platform compiling

### ISSUE THREAD

**Issue by fresheneesz** [crcn/nexe#75]
I would like to have an option to choose the platform/format to compile to. This would be something like passing in "win32" or that kind of thing, so that you can compile an executable on one system (say windows) even if its meant to be run in another (say linux).

**Comment by RainbowDashDC** [comment]
This can't *really* be done, and isn't up to nexe to provide. This is because it's created via compiling node.js. Targetting other platforms from a different platform is a gray area to begin with. While it would be a nice option I'm going to go ahead and say it won't be implemented. If you want to target another platform setup a build server running the operating system.

**Comment by liudonghua123** [comment]
We can do some research in the similar project `pkg` (https://github.com/zeit/pkg#use-cases), it can do cross-platform compiling and building.

> Instantly make executables for other platforms (cross-compilation)
